---
env:
  # browser: true
  # es2021: true
  node: true

plugins:
  - "import"

extends: 
 - 'airbnb-base'
#  - 'plugin: import'

overrides: []

parserOptions:
  ecmaVersion: latest
  # sourceType: module
  
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]